# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='app1',
            field=models.CharField(default=b'URL del app 1', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='app2',
            field=models.CharField(default=b'URL del app 2', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='app3',
            field=models.CharField(default=b'URL del app 3', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='documentacion',
            field=models.CharField(default=b'URL de la documentacion', max_length=200),
        ),
    ]
