# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20160222_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='logo',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
