# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20160223_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='respos',
            new_name='repos',
        ),
    ]
