# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_auto_20160306_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='archivo_app',
        ),
    ]
