# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_remove_producto_archivo_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='repos',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
    ]
