# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titl', models.CharField(default='Titulo predeterminado', max_length=100)),
                ('texto', models.CharField(default='Texto amigable', max_length=10000)),
                ('imagenes', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
