# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemiology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epi',
            name='distractor_1',
            field=models.CharField(default='Texto amigable', max_length=20),
        ),
        migrations.AddField(
            model_name='epi',
            name='distractor_2',
            field=models.CharField(default='Texto amigable', max_length=20),
        ),
        migrations.AddField(
            model_name='epi',
            name='distractor_3',
            field=models.CharField(default='Texto amigable', max_length=20),
        ),
        migrations.AddField(
            model_name='epi',
            name='encabezado_pregunta',
            field=models.CharField(default='Texto amigable', max_length=10000),
        ),
        migrations.AddField(
            model_name='epi',
            name='repuesta_correcta',
            field=models.CharField(default='Texto amigable', max_length=20),
        ),
    ]
