# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidemiology', '0003_epi_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epi',
            name='nombre',
        ),
    ]
